apiVersion: extensions/v1beta1
kind: Deployment				#pretty much same like ReplicationController
metadata:
  name: hello-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-web				#labels for pods.. this should be same in services
    spec:
      containers:
      - name: hello-container
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
        livenessProbe:				#healthcheck
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 30
        # env:														#using secret via env
        # 	- name: SECRET_USERNAME
        # 	  valueFrom:
        # 	  	secretKeyRef:
        # 	  		name: db-secret					#name of the secret created with secret.yml file
        # 	  		key: username
        # 	- name: SECRET_PASSWORD
        # 	  valueFrom:
        # 	  	secretKeyRef:
        # 	  		name: db-secret
        # 	  		key: password
        volumeMounts:										#using secret with volumes
        - name: credvolume
          mountPath: /etc/creds					#secrets mounted at this path inside the container or pod
          readOnly: true			
      volumes:							#volume definition .. creating of it 
      - name: credvolume
        secret:
          secretName: db-secret  


